package com.neemShade.TmTracker.pojo;
// default package
// Generated 20 Feb, 2017 8:03:33 PM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AttendanceUser generated by hbm2java
 */
@Entity
@Table(name = "tm_attendance_user", catalog = "tm")
public class AttendanceUser implements java.io.Serializable {

	private Long attendanceUserId;
	private Meeting meeting;
	private User user;
	private Boolean isPresent;

	public AttendanceUser() {
	}

	public AttendanceUser(Meeting meeting, User user) {
		this.meeting = meeting;
		this.user = user;
	}

	public AttendanceUser(Meeting meeting, User user, Boolean isPresent) {
		this.meeting = meeting;
		this.user = user;
		this.isPresent = isPresent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "attendance_user_id", unique = true, nullable = false)
	public Long getAttendanceUserId() {
		return this.attendanceUserId;
	}

	public void setAttendanceUserId(Long attendanceUserId) {
		this.attendanceUserId = attendanceUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "meeting_id", nullable = false)
	public Meeting getMeeting() {
		return this.meeting;
	}

	public void setMeeting(Meeting meeting) {
		this.meeting = meeting;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "is_present")
	public Boolean getIsPresent() {
		return this.isPresent;
	}

	public void setIsPresent(Boolean isPresent) {
		this.isPresent = isPresent;
	}

}
