package com.neemShade.TmTracker.pojo;
// default package
// Generated 20 Feb, 2017 8:03:33 PM by Hibernate Tools 5.2.0.Beta1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Meeting generated by hbm2java
 */
@Entity
@Table(name = "tm_meeting", catalog = "tm", uniqueConstraints = @UniqueConstraint(columnNames = { "club_id",
		"meeting_date" }))
public class Meeting implements java.io.Serializable {

	private Long meetingId;
	private Club club;
	private Date meetingDate;
	private String meetingTime;
	private String meetingNotes;
	@JsonIgnore
	private Set<AttendanceUser> attendanceUsers = new HashSet<AttendanceUser>(0);

	public Meeting() {
	}

	public Meeting(Club club) {
		this.club = club;
	}

	public Meeting(Club club, Date meetingDate, String meetingTime, String meetingNotes,
			Set<AttendanceUser> attendanceUsers) {
		this.club = club;
		this.meetingDate = meetingDate;
		this.meetingTime = meetingTime;
		this.meetingNotes = meetingNotes;
		this.attendanceUsers = attendanceUsers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "meeting_id", unique = true, nullable = false)
	public Long getMeetingId() {
		return this.meetingId;
	}

	public void setMeetingId(Long meetingId) {
		this.meetingId = meetingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "club_id", nullable = false)
	public Club getClub() {
		return this.club;
	}

	public void setClub(Club club) {
		this.club = club;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "meeting_date", length = 10)
	public Date getMeetingDate() {
		return this.meetingDate;
	}

	public void setMeetingDate(Date meetingDate) {
		this.meetingDate = meetingDate;
	}

	@Column(name = "meeting_time", length = 100)
	public String getMeetingTime() {
		return this.meetingTime;
	}

	public void setMeetingTime(String meetingTime) {
		this.meetingTime = meetingTime;
	}

	@Column(name = "meeting_notes", length = 2000)
	public String getMeetingNotes() {
		return this.meetingNotes;
	}

	public void setMeetingNotes(String meetingNotes) {
		this.meetingNotes = meetingNotes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "meeting")
	public Set<AttendanceUser> getAttendanceUsers() {
		return this.attendanceUsers;
	}

	public void setAttendanceUsers(Set<AttendanceUser> attendanceUsers) {
		this.attendanceUsers = attendanceUsers;
	}

}
