package com.neemShade.TmTracker.pojo;
// default package
// Generated 20 Feb, 2017 8:03:33 PM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

/**
 * ProjectType generated by hbm2java
 */
@Entity
@Table(name = "tm_project_type", catalog = "tm")
//@JsonIdentityInfo(
//		  generator = ObjectIdGenerators.PropertyGenerator.class, 
//		  property = "projectTypeId")
public class ProjectType implements java.io.Serializable {

	private Integer projectTypeId;
	private String typeName;
	private Integer peckOrder;
	private Boolean isCommunication;
	@JsonIgnore
	private Set<ProjectUser> projectUsers = new HashSet<ProjectUser>(0);

	public ProjectType() {
	}

	public ProjectType(String typeName, Integer peckOrder,
			Boolean isCommunication, Set<ProjectUser> projectUsers) {
		this.typeName = typeName;
		this.peckOrder = peckOrder;
		this.isCommunication = isCommunication;
		this.projectUsers = projectUsers;
	}
	
	@Override
	public String toString()
	{
		return typeName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "project_type_id", unique = true, nullable = false)
	public Integer getProjectTypeId() {
		return this.projectTypeId;
	}

	public void setProjectTypeId(Integer projectTypeId) {
		this.projectTypeId = projectTypeId;
	}

	@Column(name = "type_name", length = 50)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "peck_order")
	public Integer getPeckOrder() {
		return this.peckOrder;
	}

	public void setPeckOrder(Integer peckOrder) {
		this.peckOrder = peckOrder;
	}

	@Column(name = "is_communication")
	public Boolean getIsCommunication() {
		return this.isCommunication;
	}

	public void setIsCommunication(Boolean isCommunication) {
		this.isCommunication = isCommunication;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "projectType")
//	@JsonBackReference
	public Set<ProjectUser> getProjectUsers() {
		return this.projectUsers;
	}

	public void setProjectUsers(Set<ProjectUser> projectUsers) {
		this.projectUsers = projectUsers;
	}

}
